#!/usr/bin/env python3
import os
import json
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom

# Cấu hình Thương hiệu theo tên Repository của DONABICO SYSTEM
BRAND_REGISTRY = {
    "8000kicks": {
        "name": "8000Kicks Waterproof Hemp Shoes",
        "description": "Super sustainable, waterproof hemp shoes for active explorers. Natural, durable, eco-friendly.",
        "affiliate_url": "https://donabicomedia.net/gateway/8000kicks-shoes"
    },
    "default": {
        "name": "DONABICO Global Media System Partner",
        "description": "Premium global affiliate and advertising traffic-siphoning node.",
        "affiliate_url": "https://donabicomedia.net/gateway/default"
    }
}

def build_eseb_ecosystem():
    # 1. Xác định Brand dựa theo Repository
    repo_env = os.getenv('GITHUB_REPOSITORY', 'donabico-global-media/default')
    try:
        repo_name = repo_env.split('/')[-1].lower()
        owner = repo_env.split('/')[0]
    except Exception:
        repo_name = 'default'
        owner = 'donabico-global-media'
    
    brand_data = BRAND_REGISTRY.get(repo_name, BRAND_REGISTRY["default"])
    brand_data["repo_name"] = repo_name
    target_domain = f"https://{owner}.github.io/{repo_name}/"

    # 2. XUẤT FILE CẤU HÌNH JSON ĐỂ INDEX.HTML LOAD ĐỘNG
    config_path = "Protocols/eseb_global_config.json"
    os.makedirs(os.path.dirname(config_path), exist_ok=True)
    with open(config_path, 'w', encoding='utf-8') as f:
        json.dump(brand_data, f, indent=4, ensure_ascii=False)
    print(f"[+] Global config built successfully.")

    # 3. TỰ ĐỘNG BIÊN DỊCH CẦU NỐI: Bridges/SEP-Observer.js
    bridge_dir = "Bridges"
    os.makedirs(bridge_dir, exist_ok=True)
    bridge_code = f"""/**
 * DONABICO GLOBAL MEDIA SYSTEM - BRIDGES SECTOR (AUTOGENERATED BY ESEB)
 * Generation Time: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC
 */
const SEP_Observer = {{
    brand: "{brand_data['name']}",
    target: "{brand_data['affiliate_url']}",
    negotiate: function(targetUrl) {{
        console.log("[SEP-Observer] ESEB Tunnel open. Directing to:", targetUrl);
        const isBot = /bot|crawler|spider|slurp|crawl|mediapartners/i.test(navigator.userAgent);
        if (isBot) {{
            console.log("[SEP-Observer] Bot signature intercepted. Initiating siphoning flow.");
            return false;
        }}
        window.location.href = targetUrl;
    }}
}};
window.SEP_Observer = SEP_Observer;
"""
    with open(os.path.join(bridge_dir, "SEP-Observer.js"), "w", encoding="utf-8") as f:
        f.write(bridge_code)
    print("[+] Bridges/SEP-Observer.js generated successfully.")

    # 4. TỰ ĐỘNG TẠO SITEMAP.XML TRỎ VỀ TRANG CHỦ INDEX.HTML
    root = Element('urlset')
    root.set('xmlns', 'http://www.sitemaps.org/schemas/sitemap/0.9')
    
    url_node = SubElement(root, 'url')
    loc = SubElement(url_node, 'loc')
    loc.text = target_domain
    
    lastmod = SubElement(url_node, 'lastmod')
    lastmod.text = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
    
    changefreq = SubElement(url_node, 'changefreq')
    changefreq.text = 'daily'
    
    priority = SubElement(url_node, 'priority')
    priority.text = '1.0'

    xml_str = minidom.parseString(tostring(root)).toprettyxml(indent="  ", encoding="utf-8")
    with open("sitemap.xml", 'wb') as f:
        f.write(xml_str)
    print("[+] sitemap.xml generated successfully at root.")

if __name__ == "__main__":
    build_eseb_ecosystem()
