#!/usr/bin/env python3
import os
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom

# ĐĂNG KÝ HỆ THỐNG THƯƠNG HIỆU - 100% TIẾNG ANH CHUẨN QUỐC TẾ
BRAND_REGISTRY = {
    "8000kicks": {
        "name": "8000Kicks Waterproof Hemp Shoes",
        "description": "Super sustainable, waterproof hemp shoes for active explorers. Natural, durable, eco-friendly.",
        "affiliate_url": "https://donabicomedia.net/gateway/8000kicks-shoes",
        "cta_text": "ENTER OFFICIAL SHOP"
    },
    "acebeam": {
        "name": "ACEBEAM Tactical Flashlights",
        "description": "Professional-grade military illumination systems. Extreme durability, high-intensity tactical output.",
        "affiliate_url": "https://donabicomedia.net/gateway/acebeam-tactical",
        "cta_text": "ENTER OFFICIAL SHOP"
    },
    "olight": {
        "name": "Olight World-Class Illumination",
        "description": "Cutting-edge portable lighting tools for outdoor, tactical, and everyday carry enthusiasts.",
        "affiliate_url": "https://donabicomedia.net/gateway/olight-tech",
        "cta_text": "ENTER OFFICIAL SHOP"
    },
    "default": {
        "name": "DONABICO Global Media System Partner",
        "description": "Premium global affiliate and advertising traffic-siphoning node.",
        "affiliate_url": "https://donabicomedia.net/gateway/default",
        "cta_text": "ENTER OFFICIAL SHOP"
    }
}

def build_eseb_engine():
    # 1. Xác định Brand dựa theo Repository đang chạy
    repo_env = os.getenv('GITHUB_REPOSITORY', 'donabico-global-media/default')
    try:
        repo_name = repo_env.split('/')[-1].lower()
        owner = repo_env.split('/')[0]
    except Exception:
        repo_name = 'default'
        owner = 'donabico-global-media'
    
    brand = BRAND_REGISTRY.get(repo_name, BRAND_REGISTRY["default"])
    target_domain = f"https://{owner}.github.io/{repo_name}/"

    # 2. BIÊN DỊCH CẦU NỐI ĐỘNG THẲNG VÀO Bridges/SEP-Observer.js
    bridge_dir = "Bridges"
    os.makedirs(bridge_dir, exist_ok=True)
    
    # Đoạn mã JS tự thực thi (IIFE) được Python sinh ra
    js_code = f"""/**
 * DONABICO GLOBAL MEDIA SYSTEM - BRIDGES SECTOR (AUTOGENERATED BY ESEB ENGINE)
 * Updated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC
 */
(function() {{
    const brandConfig = {{
        name: "{brand['name']}",
        description: "{brand['description']}",
        target: "{brand['affiliate_url']}",
        ctaText: "{brand['cta_text']}"
    }};

    function executeHandshake() {{
        // Tự động tìm và cập nhật toàn bộ DOM Text của index.html
        const titleNode = document.getElementById('brand-title');
        const descNode = document.getElementById('brand-desc');
        const pageTitle = document.getElementById('page-title');
        const actionBtn = document.getElementById('checkout-link') || document.querySelector('.action-link');

        if (titleNode) titleNode.textContent = brandConfig.name;
        if (descNode) descNode.textContent = brandConfig.description;
        if (pageTitle) pageTitle.textContent = brandConfig.name + " | Official Gateway";
        
        if (actionBtn) {{
            actionBtn.textContent = brandConfig.ctaText.toUpperCase();
            
            // Xử lý sự kiện click chuyển hướng an toàn, triệt tiêu lỗi giật trang
            actionBtn.addEventListener('click', function(e) {{
                e.preventDefault();
                
                // Trích xuất link đích thực tế từ URL (?src=)
                const urlParams = new URLSearchParams(window.location.search);
                const targetUrl = urlParams.get('src');
                const finalDestination = targetUrl ? decodeURIComponent(targetUrl) : brandConfig.target;
                
                // Bộ lọc phát hiện Bot/Crawler
                const isBot = /bot|crawler|spider|slurp|crawl|mediapartners/i.test(navigator.userAgent);
                if (isBot) {{
                    console.log("[ESEB-Bridge] Bot detected. Navigation locked.");
                    return false;
                }}
                
                // Điều hướng an toàn cho người dùng thật
                window.location.href = finalDestination;
            }});
        }}

        // Đồng bộ SEO Meta Tags tự động cho Bot quét
        const metaDesc = document.getElementById('meta-desc') || document.querySelector('meta[name="description"]');
        const ogTitle = document.getElementById('og-title') || document.querySelector('meta[property="og:title"]');
        const ogDesc = document.getElementById('og-desc') || document.querySelector('meta[property="og:description"]');

        if (metaDesc) metaDesc.setAttribute('content', brandConfig.description);
        if (ogTitle) ogTitle.setAttribute('content', brandConfig.name);
        if (ogDesc) ogDesc.setAttribute('content', brandConfig.description);
    }}

    if (document.readyState === 'loading') {{
        document.addEventListener('DOMContentLoaded', executeHandshake);
    }} else {{
        executeHandshake();
    }}
}})();
"""
    
    with open(os.path.join(bridge_dir, "SEP-Observer.js"), "w", encoding="utf-8") as f:
        f.write(js_code)
    print("[+] Dynamic Bridge compiled successfully.")

    # 3. TỰ ĐỘNG BIÊN DỊCH SITEMAP.XML RA THƯ CỤC GỐC (ROOT)
    root = Element('urlset')
    root.set('xmlns', 'http://www.sitemaps.org/schemas/sitemap/0.9')
    
    url_node = SubElement(root, 'url')
    loc = SubElement(url_node, 'loc')
    loc.text = target_domain
    
    lastmod = SubElement(url_node, 'lastmod')
    lastmod.text = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
    
    changefreq = SubElement(url_node, 'changefreq')
    changefreq.text = 'daily'
    
    priority = SubElement(url_node, 'priority')
    priority.text = '1.0'

    xml_str = minidom.parseString(tostring(root)).toprettyxml(indent="  ", encoding="utf-8")
    with open("sitemap.xml", 'wb') as f:
        f.write(xml_str)
    print("[+] sitemap.xml generated successfully at root.")

if __name__ == "__main__":
    build_eseb_engine()
