name: DEPLOY-TO-OCEAN

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Dòng này sẽ tạo ra nút "Run workflow" cho bạn

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT CODE
        uses: actions/checkout@v4

      - name: DEPLOY TO GITHUB PAGES
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          commit_message: "DEPLOY-TO-OCEAN: MANUAL TRIGGER [V3000-Ω]"
